openapi: 3.0.0
info:
  title: Joonas Tomingas - CV API
  description: A Swagger-based documentation of Joonas Tomingas's professional profile.
  version: 1.0.0
servers:
  - url: https://cv.com/api?lang=en

paths:
  /personal-info:
    get:
      summary: Get personal information
      responses:
        '200':
          description: Personal information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalInfo'

  /education:
    get:
      summary: Get education history
      responses:
        '200':
          description: Education history
          content:
            application/json:
              schema:
                type: array
                items:
              example:
                - institution: University of Tartu
                  field: Mathematical statistics, Computer Science
                  startAt: 2016
                  endAt: 2019
                - institution: IT Technology College of Estonia
                  field: IT Systems Development
                  startAt: 2015
                  endAt: 2016  
                - institution: Hugo Treffner Gymnasium
                  field: Science
                  startAt: 2012
                  endAt: 2015

  /experience:
    get:
      summary: Get work experience
      responses:
        '200':
          description: Work experience
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkEntry'
                example:
                  - company: Astro Baltics OÜ
                    role: Software developer
                    startAt: 2024
                    endAt: 
                  - company: Riverty
                    role: Software developer
                    startAt: 2021
                    endAt: 2024  
                  - company: Jaan Poska Gymnasium
                    role: Java programming course teacher
                    startAt: 2020
                    endAt: 2021  
                  - company: Astro Baltics OÜ
                    role: Software developer
                    startAt: 2019
                    endAt: 2021  
                  - company: Estonian Literary Museum
                    role: Programmer/Data analyst
                    startAt: 2018
                    endAt: 2019

  /skills/languages:
    get:
      summary: Get spoken languages
      responses:
        '200':
          description: Languages spoken
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LanguageSkill'
                example:
                  - language: Estonian
                    proficiency: Native speaker
                  - language: English
                    proficiency: Advanced
                  - language: Russian
                    proficiency: Intermediate

  /driving-licence:
    get:
      summary: Get driving licence categories
      responses:
        '200':
          description: Driving licence info
          content:
            application/json:
              schema:
                type: object
                properties: 
                  categories:
                    type: array
                    items: 
                      type: string
                    example:
                      - A
                      - B
                      

components:
  schemas:
    PersonalInfo:
      type: object
      properties:
        name:
          type: string
          example: Joonas Tomingas
        dateOfBirth:
          type: string
          format: date
          example: 1996-01-27
        telephone:
          type: string
          example: +372 55645543
        email:
          type: string
          example: joonas2701@gmail.com
        address:
          type: string
          example: Pikk 98-14, Tartu

    EducationEntry:
      type: object
      properties:
        institution:
          type: string
        field:
          type: string
        startAt:
          type: string
        endAt:
          type: string

    WorkEntry:
      type: object
      properties:
        period:
          type: string
        company:
          type: string
        role:
          type: string

    LanguageSkill:
      type: object
      properties:
        language:
          type: string
        proficiency:
          type: string
